export const InputDetails ={
    userInpDetails: [
        {
            id: 2,
            name: 'username',
            lable: 'Username',
            type: 'text',
            placeholder: 'John23',
            required: true,
            //pattern: '^[A-Za-z0-9]{3,12}$',
            errorMsg: 'Username should be 3-12 characters & should not include any special character!',
        },
        {
            id: 3,
            name: 'name',
            lable: 'Name',
            type: 'text',
            placeholder: 'John Smith',
            required: true,
            pattern: '^[A-Za-z]{1,20}$',
            errorMsg: 'Name is required!',
        },
        {
            id: 4,
            name: 'email',
            lable: 'Email',
            type: 'email',
            placeholder: 'example@email.com',
            required: true,
            errorMsg: 'Enter a valid email!',
        },
        {
            id: 5,
            name: 'password',
            lable: 'Password',
            type: 'password',
            placeholder: 'Password',
            required: true,
            pattern: '^(?=.*[0-9])(?=.*[A-Za-z])(?=.*[!@#$%^&*()_+])[A-Za-z0-9!@#$%^&*()_+]{6,20}$',
            errorMsg:
                'Password should be 6-20 characters and include at last 1 num, 1 letter, 1 special character!',
        },
        {
            id: 6,
            name: 'address',
            lable: 'Address',
            type: 'text',
            placeholder: 'Address',
            required: true,
            errorMsg: 'Address is required!',
        },
    ],
    productInpDetails : [
        {
            id: 2,
            name: 'title',
            lable: 'Title',
            type: 'text',
            placeholder: 'Product title',
            required: true,
            errorMsg: 'Title is required!',
        },
        {
            id: 3,
            name: 'description',
            lable: 'Description',
            type: 'text',
            placeholder: 'Product description',
            required: true,
            errorMsg: 'Description is required!',
        },
        {
            id: 4,
            name: 'category',
            lable: 'Category',
            type: 'text',
            placeholder: 'Product category',
            required: true,
            errorMsg: 'Category is required!',
        },
        {
            id: 5,
            name: 'price',
            lable: 'Price',
            type: 'number',
            placeholder: 'Product price',
            required: true,
            errorMsg: 'Price is required!',
        },
        {
            id: 6,
            name: 'stock',
            lable: 'In Stock',
            type: 'text',
            placeholder: 'In Stock',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 7,
            name: 'color',
            lable: 'Mau sac',
            type: 'text',
            placeholder: 'Mau sac',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 8,
            name: 'ram',
            lable: 'Ram',
            type: 'text',
            placeholder: 'Ram',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 9,
            name: 'chip',
            lable: 'Chip',
            type: 'text',
            placeholder: 'Chip',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 10,
            name: 'batteries',
            lable: 'Pin',
            type: 'text',
            placeholder: 'Pin',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 11,
            name: 'security',
            lable: 'Bảo mật',
            type: 'text',
            placeholder: 'Bảo mật',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 12,
            name: 'waterproof',
            lable: 'Chông nước',
            type: 'text',
            placeholder: 'Chống nước',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 13,
            name: 'security',
            lable: 'Bảo mật',
            type: 'text',
            placeholder: 'Bảo mật',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 14,
            name: 'size',
            lable: 'Kích thước',
            type: 'text',
            placeholder: 'Kích thước',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 15,
            name: 'camera',
            lable: 'Camera',
            type: 'text',
            placeholder: 'Camera',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 16,
            name: 'weight',
            lable: 'Khối lượng',
            type: 'text',
            placeholder: 'Khối lượng',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 17,
            name: 'operatingSystem',
            lable: 'Hệ điều hành',
            type: 'text',
            placeholder: 'Hệ điều hành',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 18,
            name: 'origin',
            lable: 'Nguồn gốc',
            type: 'text',
            placeholder: 'Nguồn gốc',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 19,
            name: 'material',
            lable: 'Chất liệu',
            type: 'text',
            placeholder: 'Chất liệu',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 20,
            name: 'screenSize',
            lable: 'Kích thước màn hình',
            type: 'text',
            placeholder: 'Kích thước màn hình',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 21,
            name: 'accessoryType',
            lable: 'Loại phụ kiện',
            type: 'text',
            placeholder: 'Loại phụ kiện',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 22,
            name: 'technology',
            lable: 'Công Nghệ',
            type: 'text',
            placeholder: 'Công nghệ',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 23,
            name: 'wattage',
            lable: 'Công Suất',
            type: 'text',
            placeholder: 'Công Suất',
            required: true,
            errorMsg: 'This field is required!',
        },
        {
            id: 24,
            name: 'warranty',
            lable: 'Bảo Hành',
            type: 'text',
            placeholder: 'Bảo Hành',
            required: true,
            errorMsg: 'This field is required!',
        },
    ],
    blogInputs: [
        {
            id: 1,
            name: 'title',
            lable: 'Title',
            type: 'text',
            placeholder: 'Blog title',
            required: true,
            errorMsg: 'Title is required!',
        },
        {
            id: 2,
            name: 'description',
            lable: 'Description',
            type: 'text',
            placeholder: 'Blog description',
            required: true,
            errorMsg: 'Description is required!',
        },
        {
            id: 3,
            name: 'tags',
            lable: 'Tags',
            type: 'text',
            placeholder: 'Travel, Communication',
            required: true,
            errorMsg: 'Tag is required!',
        },
    ]
}