export const InputDetails ={
    userInpDetails: [
        {
            id: 2,
            name: 'username',
            lable: 'Username',
            type: 'text',
            placeholder: 'John23',
            required: true,
            //pattern: '^[A-Za-z0-9]{3,12}$',
            errorMsg: 'Username should be 3-12 characters & should not include any special character!',
        },
        {
            id: 3,
            name: 'name',
            lable: 'Name',
            type: 'text',
            placeholder: 'John Smith',
            required: true,
            pattern: '^[A-Za-z]{1,20}$',
            errorMsg: 'Name is required!',
        },
        {
            id: 4,
            name: 'email',
            lable: 'Email',
            type: 'email',
            placeholder: 'example@email.com',
            required: true,
            errorMsg: 'Enter a valid email!',
        },
        {
            id: 5,
            name: 'password',
            lable: 'Password',
            type: 'password',
            placeholder: 'Password',
            required: true,
            pattern: '^(?=.*[0-9])(?=.*[A-Za-z])(?=.*[!@#$%^&*()_+])[A-Za-z0-9!@#$%^&*()_+]{6,20}$',
            errorMsg:
                'Password should be 6-20 characters and include at last 1 num, 1 letter, 1 special character!',
        },
        {
            id: 6,
            name: 'address',
            lable: 'Address',
            type: 'text',
            placeholder: 'Address',
            required: true,
            errorMsg: 'Address is required!',
        },
    ],
    productInpDetails : [
        {
            id: 2,
            name: 'tensanpham',
            lable: 'Tên Sản Phẩm',
            type: 'text',
            placeholder: 'Product title',
            required: false,
            errorMsg: 'Title is required!',
        },
        {
            id: 3,
            name: 'loaisanpham',
            lable: 'Loại Sản Phẩm',
            type: 'text',
            placeholder: 'Product description',
            required: false,
            errorMsg: 'Description is required!',
        },
        {
            id: 4,
            name: 'hinh',
            lable: 'Hình',
            type: 'text',
            placeholder: 'Product category',
            required: false,
            errorMsg: 'Category is required!',
        },
        {
            id: 5,
            name: 'gia',
            lable: 'Giá',
            type: 'number',
            placeholder: 'Product price',
            required: false,
            errorMsg: 'Price is required!',
        },
        {
            id: 6,
            name: 'rom',
            lable: 'ROM',
            type: 'text',
            placeholder: 'ROM',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 7,
            name: 'mausac',
            lable: 'Màu sắc',
            type: 'text',
            placeholder: 'Màu sắc',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 8,
            name: 'ram',
            lable: 'Ram',
            type: 'number',
            placeholder: 'Ram',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 9,
            name: 'chip',
            lable: 'Chip',
            type: 'text',
            placeholder: 'Chip',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 10,
            name: 'baomat',
            lable: 'Bảo mật',
            type: 'text',
            placeholder: 'Bảo mật',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 11,
            name: 'chongnuoc',
            lable: 'Chông nước',
            type: 'text',
            placeholder: 'Chống nước',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 12,
            name: 'sac',
            lable: 'Sạc',
            type: 'text',
            placeholder: 'Sạc',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 13,
            name: 'dophangiai',
            lable: 'Độ Phân Giải',
            type: 'text',
            placeholder: 'Độ Phân Giải',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 14,
            name: 'kichthuoc',
            lable: 'Kích thước',
            type: 'text',
            placeholder: 'Kích thước',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 15,
            name: 'camera',
            lable: 'Camera',
            type: 'text',
            placeholder: 'Camera',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 16,
            name: 'khoiluong',
            lable: 'Khối lượng',
            type: 'text',
            placeholder: 'Khối lượng',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 17,
            name: 'hedieuhanh',
            lable: 'Hệ điều hành',
            type: 'text',
            placeholder: 'Hệ điều hành',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 18,
            name: 'nguongoc',
            lable: 'Nguồn gốc',
            type: 'text',
            placeholder: 'Nguồn gốc',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 19,
            name: 'chatlieu',
            lable: 'Chất liệu',
            type: 'text',
            placeholder: 'Chất liệu',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 20,
            name: 'kichthuocmanhinh',
            lable: 'Kích thước màn hình',
            type: 'text',
            placeholder: 'Kích thước màn hình',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 21,
            name: 'loaiphukien',
            lable: 'Loại phụ kiện',
            type: 'text',
            placeholder: 'Loại phụ kiện',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 22,
            name: 'congnghe',
            lable: 'Công Nghệ',
            type: 'text',
            placeholder: 'Công nghệ',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 23,
            name: 'congsuat',
            lable: 'Công Suất',
            type: 'text',
            placeholder: 'Công Suất',
            required: false,
            errorMsg: 'This field is required!',
        },
        {
            id: 24,
            name: 'baohanh',
            lable: 'Bảo Hành',
            type: 'text',
            placeholder: 'Bảo Hành',
            required: false,
            errorMsg: 'This field is required!',
        },
    ],
    blogInputs: [
        {
            id: 1,
            name: 'title',
            lable: 'Title',
            type: 'text',
            placeholder: 'Blog title',
            required: true,
            errorMsg: 'Title is required!',
        },
        {
            id: 2,
            name: 'description',
            lable: 'Description',
            type: 'text',
            placeholder: 'Blog description',
            required: true,
            errorMsg: 'Description is required!',
        },
        {
            id: 3,
            name: 'tags',
            lable: 'Tags',
            type: 'text',
            placeholder: 'Travel, Communication',
            required: true,
            errorMsg: 'Tag is required!',
        },
    ]
}